//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by FrontCad.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_FrontCadTYPE                130
#define ID_WINDOW_MANAGER               131
#define IDD_DIALOG_RENDER_ENABLE        144
#define IDD_CDlgRoundHoleProp           311
#define IDD_DIALOG_DIMENSION_PROPERTIES 312
#define IDD_DLG_NEW_DRAWING             314
#define IDD_DIALOG_TEXT_PROPERTIES      326
#define IDD_DIALOG_LINE_ATTRB           328
#define IDD_DIALOG_RECTPROPERTIES       330
#define IDD_DIALOG_ELLIPSE_PROPERTIES   332
#define IDD_DIALOG_ROUNDEDRECT_PROPERTIES 336
#define IDD_DIALOG_BITMAP_PROPERTIES    338
#define IDD_DIALOG_ARCPROPERTIES        340
#define IDD_DIALOG_ARCCENTPROPERTIES    341
#define IDD_DIALOG_POLY_EDPROPERTIES    342
#define IDD_DIALOG_ARROW_ATTRIBUTES     343
#define IDD_DIALOG_NEWNAME              349
#define IDD_DIALOG_RNDHOLE1FLATPROP     356
#define IDD_DIALOG_RNDHOLE2FLATPROP     357
#define IDD_CDlgSquareHoleProp          358
#define IDC_STATIC_DIM_PREVIW           1003
#define IDC_EDIT_DIM_TEXT               1004
#define IDC_STATIC_PREVIEW              1005
#define IDC_EDIT4                       1005
#define IDC_EDIT_EXTENSION_LENGTH       1005
#define IDC_CHECK_LINEPROP_LOCKLEN      1008
#define IDC_EDIT_NEWDRAWON_NAME         1009
#define IDC_EDIT_NEWDRAWING_pAPERSIZE_h 1010
#define IDC_EDIT_NEWDRAWING_PAPERSIZE_W 1011
#define IDC_EDIT_DRAWINGSIZE_H          1012
#define IDC_EDIT_DRAWOMGSOZE_W          1013
#define IDC_EDIT_TEXT_STRING            1014
#define IDC_BUTTON1                     1014
#define IDC_BUTTON_OPEN_EXISTING        1014
#define IDC_CHECK_TRANSPARENT           1015
#define IDC_STATIC_TEXT_COLOR           1016
#define IDC_STATIC_BACKGROUND_COLOR     1017
#define IDC_EDIT_TEXT_HEIGHT            1018
#define IDC_EDIT_TEXT_WIDTH             1019
#define IDC_BUTTON_FONT                 1020
#define IDC_COMBO_FONTWEIGHT            1021
#define IDC_EDIT_ANGLE                  1022
#define IDC_EDIT_LINE_WIDTH             1023
#define IDC_STATIC_LINE_COLOR           1024
#define IDC_DLGLINE_STATIC_FILL_COLOR   1025
#define IDC_STATIC_FILL_COLOR           1026
#define IDC_STATIC_LINECOLOR            1028
#define IDC_STATIC_FILLCOLOR            1029
#define IDC_EDIT_LINEWIDTH              1031
#define IDC_EDIT_CORNERRADIUS           1033
#define IDC_EDIT_CORNERRADIUS_Y         1034
#define IDC_CHECK_MAINTAIN_ASPECT_RATIO 1035
#define IDC_EDIT_FILENAME               1036
#define IDC_BUTTON_CHOOSE_FILE          1037
#define IDC_EDIT_START_X                1039
#define IDC_EDIT_START_Y                1040
#define IDC_EDIT_END_X                  1041
#define IDC_EDIT_END_Y                  1042
#define IDC_EDIT_START_ANGLE            1043
#define IDC_EDIT_END_ANGLE              1044
#define IDC_EDIT_L1                     1045
#define IDC_EDIT_L2                     1046
#define IDC_STATIC_COLOR                1047
#define IDC_EDIT_WIDTH                  1048
#define IDC_RNDHOLE1FLAT_WIDTH          1049
#define IDC_EDIT_NEWNAME                1049
#define IDC_EDIT_ROUNDHOLE_RADIUS       1049
#define IDC_RNDHOLE1FLAT_RADIUS         1050
#define IDC_EDIT_ROUNDHOLE_WIDTH        1050
#define IDC_RNDHOLE1FLAT_FLAT           1051
#define IIDC_CHECK_RECT_NOFILL          1057
#define IDC_CHECK_ELLIPSE_NOFILL        1058
#define IDC_CHECK_POLYGON_NOFILL        1060
#define IDC_CHECK_RNDRECT_NOFILL        1061
#define IDC_STATIC_ROUNDHOLE_COLOR      1063
#define IDC_RNDHOLE1FLAT_COLOR          1064
#define IDC_CHECK_LINEENABLE            1107
#define IDC_CHECK_RECTENABLE            1108
#define IDC_CHECK_ROUNDEDRECTENABLE     1109
#define IDC_CHECK_ELLISPEENABLE         1110
#define IDC_CHECK_POLYGONENABLE         1111
#define IDC_CHECK_FILLEDPOLYENABLE      1112
#define IDC_CHECK_ARCENABLE             1113
#define IDC_CHECK_ARCCENTEREDENABLE     1114
#define IDC_CHECK_TEXTENABLED           1115
#define IDC_CHECK_ROUNDHOLEENABLE       1116
#define IDC_CHECK_ONEFLATENABLE         1117
#define IDC_CHECK_TWOFLATENABLE         1119
#define IDC_CHECK_RECTHOLEENABLE        1120
#define IDC_CHECK_ARROWENABLE           1121
#define IDC_CHECK_ORIGINENABLE          1122
#define IDC_CHECK_DIMENSIONENABLE       1123
#define ID_DRAW_POINT                   32771
#define ID_DRAW_LINE                    32772
#define ID_DRAW_ARDC                    32773
#define ID_DRAW_ARCCNTER                32774
#define ID_DRAW_ARCANGLE                32775
#define ID_DRAW_ELLIPSE                 32776
#define ID_DRAW_RECTANGLE               32777
#define ID_DRAW_ROTATEDRECTANGLE        32778
#define ID_DRAW_ROUNDEDRECTANGLE        32779
#define ID_DRAW_POLYGOHN                32780
#define ID_DRAW_TEXT                    32781
#define ID_DRAW_ROUNDHOLE               32782
#define ID_DRAW_ROUNDHOLEWITH1FLAT      32783
#define ID_DRAW_ROUNDHOLEWITH2FLATS     32784
#define ID_DRAW_RECTANGULARHOLE         32785
#define ID_DRAW_ORIGIN                  32786
#define ID_DRAW_DIMENSION               32787
#define ID_MODIFY_MOVEPOINT             32788
#define ID_MODIFY_LINE                  32789
#define ID_LINE_DRAGENDPOINT            32790
#define ID_LINE_ROTATEAROUNDREF         32791
#define ID_LINE_LOCKLINELEGNTH          32792
#define ID_MODIFY_REC                   32793
#define ID_RECTANGLE_DRAGEPOINT         32794
#define ID_RECTANGLE_DRAGRECTANGLE      32795
#define ID_SNAP_SNAPGRIDPROPERTIES      32796
#define ID_SNAP_SNAPGRIDON              32797
#define ID_SNAP_SNAPTOOBJECT            32798
#define ID_SNAP_SNAPTOTANGENT           32799
#define ID_VIEW_ZOOMIN                  32800
#define ID_VIEW_ZOOMOUT                 32801
#define ID_DRAW_PLACEBITMAP             32802
#define ID_DRAW_ARROW                   32803

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        316
#define _APS_NEXT_COMMAND_VALUE         32804
#define _APS_NEXT_CONTROL_VALUE         1015
#define _APS_NEXT_SYMED_VALUE           311
#endif
#endif
